# Generated by Django 5.0.4 on 2024-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default='Mtech', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(default='programming'),
        ),
    ]
