# Generated by Django 5.0.4 on 2024-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher_qualification_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.TextField(),
        ),
    ]
