# Generated by Django 5.0.4 on 2024-04-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teacher_qualification_alter_teacher_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='mobile_no',
            new_name='mobileno',
        ),
    ]
