# Generated by Django 5.0.4 on 2024-04-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_full_name_teacher_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featuredimage',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachnologies',
            field=models.TextField(null=True),
        ),
    ]
