# Generated by Django 5.0.4 on 2024-04-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_mobile_no_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='interested_categories',
            new_name='interests',
        ),
    ]
